<?php

/**
 * BaseSeasons
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $name
 * @property varchar $event
 * @property timestamp $start
 * @property timestamp $end
 * @property varchar $link
 * @property Doctrine_Collection $Matchs
 * @property Doctrine_Collection $Teams
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method varchar             getName()   Returns the current record's "name" value
 * @method varchar             getEvent()  Returns the current record's "event" value
 * @method timestamp           getStart()  Returns the current record's "start" value
 * @method timestamp           getEnd()    Returns the current record's "end" value
 * @method varchar             getLink()   Returns the current record's "link" value
 * @method Doctrine_Collection getMatchs() Returns the current record's "Matchs" collection
 * @method Doctrine_Collection getTeams()  Returns the current record's "Teams" collection
 * @method Seasons             setId()     Sets the current record's "id" value
 * @method Seasons             setName()   Sets the current record's "name" value
 * @method Seasons             setEvent()  Sets the current record's "event" value
 * @method Seasons             setStart()  Sets the current record's "start" value
 * @method Seasons             setEnd()    Sets the current record's "end" value
 * @method Seasons             setLink()   Sets the current record's "link" value
 * @method Seasons             setMatchs() Sets the current record's "Matchs" collection
 * @method Seasons             setTeams()  Sets the current record's "Teams" collection
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeasons extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seasons');
        $this->hasColumn('id', 'integer', 20, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 20,
             ));
        $this->hasColumn('name', 'varchar', 50, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('event', 'varchar', 50, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('start', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('end', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('link', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Matchs', array(
             'local' => 'id',
             'foreign' => 'season_id'));

        $this->hasMany('Teams', array(
             'local' => 'id',
             'foreign' => 'season_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}