<?php

/**
 * BaseTeamsInSeasons
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $season_id
 * @property integer $team_id
 * @property Seasons $Seasons
 * @property Teams $Teams
 * 
 * @method integer        getId()        Returns the current record's "id" value
 * @method integer        getSeasonId()  Returns the current record's "season_id" value
 * @method integer        getTeamId()    Returns the current record's "team_id" value
 * @method Seasons        getSeasons()   Returns the current record's "Seasons" value
 * @method Teams          getTeams()     Returns the current record's "Teams" value
 * @method TeamsInSeasons setId()        Sets the current record's "id" value
 * @method TeamsInSeasons setSeasonId()  Sets the current record's "season_id" value
 * @method TeamsInSeasons setTeamId()    Sets the current record's "team_id" value
 * @method TeamsInSeasons setSeasons()   Sets the current record's "Seasons" value
 * @method TeamsInSeasons setTeams()     Sets the current record's "Teams" value
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeamsInSeasons extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('teams_in_seasons');
        $this->hasColumn('id', 'integer', 20, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 20,
             ));
        $this->hasColumn('season_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
        $this->hasColumn('team_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Seasons', array(
             'local' => 'season_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Teams', array(
             'local' => 'team_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}