<?php

/**
 * BaseTeams
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $name
 * @property varchar $shorthandle
 * @property varchar $flag
 * @property varchar $link
 * @property Doctrine_Collection $Matchs
 * @property Doctrine_Collection $TeamsInSeasons
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method varchar             getName()           Returns the current record's "name" value
 * @method varchar             getShorthandle()    Returns the current record's "shorthandle" value
 * @method varchar             getFlag()           Returns the current record's "flag" value
 * @method varchar             getLink()           Returns the current record's "link" value
 * @method Doctrine_Collection getMatchs()         Returns the current record's "Matchs" collection
 * @method Doctrine_Collection getTeamsInSeasons() Returns the current record's "TeamsInSeasons" collection
 * @method Teams               setId()             Sets the current record's "id" value
 * @method Teams               setName()           Sets the current record's "name" value
 * @method Teams               setShorthandle()    Sets the current record's "shorthandle" value
 * @method Teams               setFlag()           Sets the current record's "flag" value
 * @method Teams               setLink()           Sets the current record's "link" value
 * @method Teams               setMatchs()         Sets the current record's "Matchs" collection
 * @method Teams               setTeamsInSeasons() Sets the current record's "TeamsInSeasons" collection
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeams extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('teams');
        $this->hasColumn('id', 'integer', 20, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 20,
             ));
        $this->hasColumn('name', 'varchar', 50, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('shorthandle', 'varchar', 50, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('flag', 'varchar', 2, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('link', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Matchs', array(
             'local' => 'id',
             'foreign' => 'team_a'));

        $this->hasMany('TeamsInSeasons', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}