# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/12-Filters

rendering: ~
security:  ~

#myAuth:
#    class: myAuth

# insert your own filters here

cache:     ~
execution: ~
