<?php

/**
 * PluginsfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsfGuardUserProfile extends BasesfGuardUserProfile
{
    /**
     * Returns joind firstname and lastname as fullname.
     * @return string
     * @author fizyk
     */
    public function getFullname()
    {
        return trim( $this->getFirstname().' '.$this->getLastname() );
    }
    
    /**
     * Returns user's email address
     * @return type 
     * @deprecated depreciated since version 1.5
     * @see sfGuardUser::getEmailAddress()
     */
    public function getEmail()
    {
        return $this->getUser()->getEmailAddress();
    }
    
    /**
     * Set's user email address
     * @param type $email 
     * @deprecated depreciated since version 1.5
     * @see sfGuardUser::getEmailAddress()
     */
    public function setEmail( $email )
    {
        $this->getUser()->setEmailAddress($email);
    }

    public function  __toString()
    {
        if( $this->getFirstname() !== null || $this->getLastname() !== null  )
        {
            return $this->getLastname();
        }
        else
        {
            return $this->getUser()->getUsername();
        }
    }
}