<?php

/**
 * AdvertisingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdvertisingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdvertisingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Advertising');
    }
}