<?php

/**
 * ConfigsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConfigsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConfigsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Configs');
    }
}