<?php

/**
 * MapsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MapsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MapsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Maps');
    }
}