<?php

/**
 * MapsScoreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MapsScoreTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MapsScoreTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MapsScore');
    }
}