<?php

/**
 * PlayersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlayersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlayersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Players');
    }
}