<?php

/**
 * PlayersHeatmapTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlayersHeatmapTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlayersHeatmapTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlayersHeatmap');
    }
}