<?php

/**
 * PlayersSnapshotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlayersSnapshotTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlayersSnapshotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlayersSnapshot');
    }
}