<?php

/**
 * PlayerKillTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlayerKillTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlayerKillTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlayerKill');
    }
}