<?php

/**
 * RoundSummary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RoundSummary extends BaseRoundSummary {
    
    public function getPlayersKill() {
        return PlayerKillTable::getInstance()->createQuery()->where("round_id = ?", $this->getRoundId())->andWhere("map_id = ?", $this->getMapId())->orderBy("id ASC")->execute();
    }
    
}