<?php

/**
 * RoundSummaryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoundSummaryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoundSummaryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RoundSummary');
    }
}