<?php

/**
 * SeasonsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeasonsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeasonsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Seasons');
    }
}