<?php

/**
 * Servers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PhpProject1
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Servers extends BaseServers {

    public function __toString() {
        return $this->getIp();
    }

    public function used() {
        return MatchsTable::getInstance()->createQuery()->where("enable = ?", 1)->andWhere("status < ?", Matchs::STATUS_END_MATCH)->andWhere("server_id = ?", $this->getId())->count() != 0;
    }

    public function getNbMatchs() {
        return MatchsTable::getInstance()->createQuery()->andWhere("server_id = ?", $this->getId())->count();
    }

    public function getStats() {
        $data = Doctrine_Query::create()
                ->select('SUM(hs) AS total_hs, SUM(nb_kill) as total_kill')
                ->from('players p')
                ->leftJoin("p.Match m")
                ->where("m.server_id = ?",$this->getId())
                ->fetchOne();
        
        return $data;
    }

}