# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:

sfForkedApply:
  from:
    email: "mail@csgolive.eslproseries.de"
    fullname: "ESL.eu"
# that section is as a fallback only
sfApplyPlugin:
  from:
    email: "mail@csgolive.eslproseries.de"
    fullname: "ESL.eu"
