<?php

/**
 * sfGuardRememberKeyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardRememberKeyTable extends PluginsfGuardRememberKeyTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardRememberKeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardRememberKey');
    }
}