<?php

/**
 * sfGuardGroupPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupPermissionTable extends PluginsfGuardGroupPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardGroupPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardGroupPermission');
    }
}