<?php

/**
 * sfGuardUserProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserProfileTable extends PluginsfGuardUserProfileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserProfile');
    }
}