create:
  is_secure: true
  credentials: [[ "Manage Matches" ]]
edit:
  is_secure: true
  credentials: [[ "Edit Matches" ]]
editScore:
  is_secure: true
  credentials: [[ "Edit Matches" ]]
delete:
  is_secure: true
  credentials: [[ "Delete Match" ]]
matchsInProgress:
  is_secure: true
  credentials: [[ "View Matches", "Manage Matches" ]]
archiveAll:
  is_secure: true
  credentials: [ "Manage Matches" ]
filters:
  is_secure: true
  credentials: [ "View Matches" ]
filtersClear:
  is_secure: true
  credentials: [ "View Matches" ]
forceKnife:
  is_secure: true
  credentials: [ "Manage Matches" ]
forceKnifeEnd:
  is_secure: true
  credentials: [ "Manage Matches" ]
forceStart:
  is_secure: true
  credentials: [ "Manage Matches" ]
heatmapData:
  is_secure: true
  credentials: [ "View Matches" ]
logs:
  is_secure: true
  credentials: [ "View Matches" ]
matchsArchived:
  is_secure: true
  credentials: [ "View Matches" ]
openRcon:
  is_secure: true
  credentials: [ "Manage Matches" ]
passKnife:
  is_secure: true
  credentials: [ "Manage Matches" ]
pauseUnpause:
  is_secure: true
  credentials: [ "Manage Matches" ]
reset:
  is_secure: true
  credentials: [ "Manage Matches" ]
setArchive:
  is_secure: true
  credentials: [ "Manage Matches" ]
start:
  is_secure: true
  credentials: [ "Manage Matches" ]
startAll:
  is_secure: true
  credentials: [ "Manage Matches" ]
startRetry:
  is_secure: true
  credentials: [ "Manage Matches" ]
stop:
  is_secure: true
  credentials: [ "Manage Matches" ]
stopBack:
  is_secure: true
  credentials: [ "Manage Matches" ]
stopRS:
  is_secure: true
  credentials: [ "Manage Matches" ]
view:
  is_secure: true
  credentials: [ "View Matches" ]
